database:
  user: "daysling"
  pwd: "*******"
  host: "localhost"
  port: 3306
  database: "newsdb"
  table: news
api-key: "*******"
sources:
  - "abc-news"
  - "abc-news-au"
  - "al-jazeera-english"
  - "ars-technica"
  - "associated-press"
  - "australian-financial-review"
  - "axios"
  - "bbc-news"
  - "bbc-sport"
  - "bleacher-report"

scheduler:
  # measured in hours
  enable: true
  interval: 24
  last-ran: "2006-01-02T15:04:05Z07:00"
  # runs every 24 hours or later, use crontab to schedule to run every hour.
# WARNING: NO COMMENTS ARE PRESERVED IN THE YAML FILE IF USING SCHEDULER
